---
title: "check"
author: "Caroline Wheeler"
date: "11/29/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggforce)
```

```{r}
ra <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_RA-with-taxonomy.csv") 
k2 <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_counts-with-taxonomy.csv")
counts <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_unnormalized-microbes-with-taxonomy.csv")

clin <- read.table("/fs/ess/PAS1695/projects/exorien/data/IO_NOVA_clin.txt", header = TRUE) %>%
  dplyr::rename("sample" = Sample_ID,
         "IO.responder" = Response) %>%
  filter(Cancer_Type == "Melanoma") %>%
  dplyr::select(sample, IO.responder) %>%
  mutate(Response = ifelse(IO.responder == 0, "Non-Responder", "Responder"))
```

```{r}
ra.fus <- ra %>%
  filter(sample %in% clin$sample) %>%
  left_join(clin) %>%
  #filter(phylum == "p__Fusobacteria")
  filter(microbe == "Fusobacterium.nucleatum")
  
ra.fus.counts <- ra.fus %>%
   mutate(count = round(exo.ra*1e9)) 

counts.fus <- counts %>%
  filter(sample %in% clin$sample) %>%
  left_join(clin) %>%
  #filter(phylum == "p__Fusobacteria")
  filter(microbe == "Fusobacterium.nucleatum")
```

plot
```{r}
ra.fus %>%
  ggplot(aes(y=log(exo.ra))) +
  geom_boxplot() +
  facet_row(vars(Response), scales = "free_x", space = "free") +
  theme_bw() +
  ggtitle("RelAbun")

ra.fus.counts %>%
  ggplot(aes(y= log(count))) +
  geom_boxplot() +
  facet_row(vars(Response), scales = "free_x", space = "free") +
  theme_bw() +
  ggtitle("RelAbun estimated counts")

counts.fus %>%
  ggplot(aes(y=log(count))) +
  geom_boxplot() +
  facet_row(vars(Response), scales = "free_x", space = "free") +
  theme_bw() +
  ggtitle("Counts")
```

