---
title: "Figure 5"
output: html_document
date: "2023-02-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Figure 5: Random Forest Model Plot #

**Necessary Data**
- Scored_IO_NOVA.rda
- IO_NOVA_Mel Clinical Data
- Microbe Data
- IOSig_Signatures

```{r Necessary Packages}
library(tidyverse)
library(randomForest)
library(ggplot2)
library(ROCR)
library(gdata)
library(ggpubr)
```

```{r Load in Data, include=FALSE}
load("Data/Scored_IO_NOVA.rda")
load("Data/IOSig_Signatures.rda")
microbe_data <- readr::read_csv("Data/Microbes.csv")
clin_data <- readr::read_tsv("Data/IO_NOVA_mel_clin.txt")
```

```{r Necessary Functions}

# Main function call to generate RF models using 5 seeds #
kTest <- function(clin, feature, seeds){
  out <- list()
  for(i in 1:length(seeds)){
    out[[i]] <- k_validate(clin, feature, seed = seeds[i])
  }
  out <- grabVals(out)
  out
}

# Grabbing AUROC values from input models #
grabVals <- function(input){
  out <- list()
  for(i in 1:5){
    for(j in 1:5){
      out <- append(out, input[[i]][[j]][[1]])
    }
  }
  out
}

# Function create and test RF model #
getROC <- function(train, clin.train, test, clin.test){
  model.training <- randomForest(x = train[,-1, drop=FALSE], y = as.factor(clin.train$response))
  test.preds <- predict(model.training, test[,-1, drop=FALSE])
  
  print(model.training)
  # Check variable importance
  varImpPlot(model.training)
  # Prediction confusion matrix
  table(observed = clin.test$response, predicted = test.preds)
  
  prediction_for_roc_curve <- predict(model.training,test[,-1, drop=FALSE],type="prob")
  pred <- prediction(prediction_for_roc_curve[,2], clin.test$response, label.ordering = c("non-responder", "responder"))
  perf <- performance(pred, "tpr", "fpr")
  
  auc_ROCR <- performance(pred, measure = "auc")
  print(auc_ROCR)
  auc <- auc_ROCR@y.values[[1]]
  print(auc)
  
  df <- data.frame(FalsePositive=c(perf@x.values[[1]]),
                   TruePositive=c(perf@y.values[[1]]))
  out <- list(auc, df)
  
  return(out)
}

# Shuffling and creating training / testing groups for getROC #
k_validate <- function(clin_data, feature_data, seed){
  set.seed(seed)
  
  # Grab responder samples #
  responder_clin <- clin_data %>%
    dplyr::filter(response == "responder")
  # Shuffle responder samples via seed #
  responder_clin <- responder_clin[sample(nrow(responder_clin)), ]
  
  # Grab non-responder samples #
  non_responder_clin <- clin_data %>%
    dplyr::filter(response == 'non-responder')
  # Shuffle non-responder samples via seed #
  non_responder_clin <- non_responder_clin[sample(nrow(non_responder_clin)), ]

    # Creating index data frame for the R/NRs to ensure coverage for each group #
    responder_indexes <- c(rep(1, 8), rep(2, 8), rep(3, 8), rep(4, 8), rep(5, 7))
    non_responder_indexes <- c(rep(1, 6), rep(2, 7), rep(3, 6), rep(4, 7), rep(5, 6))
    out <- list()
    
    # Creating testing and training groups #
    for(i in 1:5){
      rIndexes <- which(responder_indexes == i, arr.ind = TRUE)
      nrIndexes <- which(non_responder_indexes == i, arr.ind = TRUE)
      
      test.clin <- rbind(responder_clin[rIndexes, ], non_responder_clin[nrIndexes, ])
      train.clin <- rbind(responder_clin[-rIndexes, ], non_responder_clin[-nrIndexes, ])
      
      test.seq <- feature_data[which(feature_data$Sample_ID %in% test.clin$Sample_ID), ]
      test.seq <- test.seq[match(test.clin$Sample_ID, test.seq$Sample_ID), ]
      
      train.seq <- feature_data[which(feature_data$Sample_ID %in% train.clin$Sample_ID), ]
      train.seq <- train.seq[match(train.clin$Sample_ID, train.seq$Sample_ID), ]
      
      if(all(train.seq$Sample_ID == train.clin$Sample_ID) == FALSE){
        stop("Training Sample_IDs do not match")
      }
      if(all(test.seq$Sample_ID == test.clin$Sample_ID) == FALSE){
        stop("Testing Sample_IDs do not match")
      }
      
      # Creating the RF model #
      out[[i]] <- getROC(train.seq, train.clin, test.seq, test.clin)
    }
  
  
  avg_auc <- lapply(out, function(x){ x[[1]]})
  message("\nAccuracy average: ", (rowMeans(as.data.frame(avg_auc))))
  return(out)
}
```

```{r Prepare Datasets}

# Signatures selected due to Mann Whitney Adj.P < 0.05 #
filtered_sigs <- c("Effector_T", "INFg_Effector", "IFNG6", "Immune_Cytolytic",
                   "TIP_Hot", "Immune_Infiltration", "IFNG18", "Chemokines",
                   "TCR_Signaling", "Ipi_Neoadjuvant", "Roh_Immune_Score", "Neoadjuvant_Response",
                   "MHC_II", "mMDSC", "Ock_Immune_Score", "IMPRES")

# Matching expression data sample IDs with the clinical data Sample IDs #
Scored_IO_NOVA <- Scored_IO_NOVA[match(clin_data$Sample_ID, Scored_IO_NOVA$Sample_ID), ]
microbe_data <- microbe_data[match(clin_data$Sample_ID, microbe_data$Sample_ID), ]
Filtered_IO_NOVA <- Scored_IO_NOVA[, which(colnames(Scored_IO_NOVA) %in% c("Sample_ID", filtered_sigs))]
AllZ_Microbe <- merge(Scored_IO_NOVA, microbe_data)
FiltZ_Microbe <- merge(Filtered_IO_NOVA, microbe_data)

clin_data$response <- ifelse(clin_data$response == 1, "responder", "non-responder")
```

```{r Generate Models, include=FALSE}
seed_list <- c(12345, 12346, 12347, 12348, 12349)

IO_NOVA_results <- kTest(clin_data, Scored_IO_NOVA, seed_list)
Microbe_results <- kTest(clin_data, microbe_data, seed_list)
Filtered_NOVA_results <- kTest(clin_data, Filtered_IO_NOVA, seed_list)
AllZ_Microbe_results <- kTest(clin_data, AllZ_Microbe, seed_list)
FiltZ_Microbe_results <- kTest(clin_data, FiltZ_Microbe, seed_list)
```

```{r Shape Model Results}
Results <- data.frame(
  unlist(IO_NOVA_results),
  unlist(Microbe_results),
  unlist(Filtered_NOVA_results),
  unlist(AllZ_Microbe_results),
  unlist(FiltZ_Microbe_results)
)
colnames(Results) <- c("GeneSig_Z_Score", 
                       "Microbe", 
                       "Imm_Act_Z_Score", 
                       "GeneSig_Z_Microbe", 
                       "Imm_Act_Z_Microbe")

Results <- tidyr::pivot_longer(Results, cols = dplyr::everything(), names_to = "Model", values_to = "AUROC")
Means <- Results %>%
  dplyr::group_by(Model) %>%
  dplyr::mutate(Model_Mean = mean(AUROC)) %>%
  dplyr::select(Model, Model_Mean) %>%
  dplyr::distinct() %>%
  dplyr::arrange(desc(Model_Mean))
Means$Model <- factor(Means$Model, levels = unique(Means$Model))
mean_order <- rev(levels(Means$Model))
```

```{r Plot Generation}
Model_Comparison_Plot <- ggplot(Results, aes(x = forcats::fct_relevel(Model, mean_order), y = AUROC, color = Model)) +
  geom_boxplot(outlier.colour = NA, fatten = NULL) + 
  geom_jitter() +
  labs(y = "AUROC", x = "Model", title = "Random Forest AUROC Model Comparison") +
  theme(axis.title = element_text(face = 'bold', size = '16'),
        axis.text.x = element_text(size = 10, face = 'bold'),
        plot.title = element_text(face = 'bold', hjust = 0.5, size = 14),
        axis.title.y = element_text(hjust = 0.45),
        legend.position = "bottom",
        axis.line = element_line(color = 'black', linewidth = 0.5),
        panel.background = element_rect(fill = 'white')) +
  scale_y_continuous(limits= c(0, 1.35), breaks=seq(0,1, 0.1)) +  # 1.35
  annotate(geom = "text", x = 3, y = 0.25, label = "Mean AUROC", color = 'black', size = 5) +
  annotate(geom="text", x=1, y=0.05, label=round(Means[5,2], 3),
            color="black", size=4) +
  annotate(geom="text", x=2, y=0.05, label=round(Means[4,2], 3),
            color="black", size=4) +
  annotate(geom="text", x=3, y=0.05, label=round(Means[3,2], 3),
            color="black", size=4) +
  annotate(geom="text", x=4, y=0.05, label=round(Means[2,2], 3),
            color="black", size=4) +
  annotate(geom="text", x=5, y=0.05, label=round(Means[1,2], 3),
            color="black", size=4)

# model_comparison <- list(
#   c("Imm_Act_Z_Microbe", "GeneSig_Z_Microbe"),
#   c("Imm_Act_Z_Microbe", "Imm_Act_Z_Score"),
#   c("Imm_Act_Z_Microbe", "GeneSig_Z_Score"),
#   c("Imm_Act_Z_Microbe", "Microbe"),
#   c("GeneSig_Z_Microbe", "Imm_Act_Z_Score"),
#   c("GeneSig_Z_Microbe", "GeneSig_Z_Score"),
#   c("GeneSig_Z_Microbe", "Microbe"),
#   c("Imm_Act_Z_Score", "GeneSig_Z_Score"),
#   c("Imm_Act_Z_Score", "Microbe"),
#   c("GeneSig_Z_Score", "Microbe")
# )

significant_comparisons <- list(
  c("Microbe", "Imm_Act_Z_Score"),
  c("Microbe", "GeneSig_Z_Microbe"),
  c("Microbe", "Imm_Act_Z_Microbe"),
  c("GeneSig_Z_Score", "Imm_Act_Z_Microbe")
)

Model_Comparison_Plot <- Model_Comparison_Plot +
     ggpubr::stat_compare_means(comparisons = significant_comparisons, 
                                label = 'p.signif', 
                                label.y = seq(0.95, by = 0.1, length.out = 4)) + 
  stat_summary(geom = "errorbar", fun.min = mean, fun = mean, fun.max = mean, width = .75)


Model_Comparison_Plot

```




