---
title: "exomel clinical info"
author: "Caroline Wheeler"
date: "7/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tableone)
library(ggplot2)
library(ggalt)
```

read in data
```{r}
response <- read.table("/fs/ess/PAS1695/projects/exorien/data/IO_NOVA_clin.txt", header = TRUE)
io <- read.csv("/fs/ess/PAS1695/projects/exorien/data/pfs_IO.csv")
clin <- read.csv("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210712_ClinicalMolLinkage_V4.csv")
extra_clin <- read.csv("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210712_PatientMaster_V4.csv")
hist <- read.csv("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210712_PatientHistory_V4.csv")
diagnosis <- read.csv("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210712_Diagnosis_V4.csv")
time <- readxl::read_xlsx("/fs/ess/PAS1695/projects/exorien/data/MEL_ICB_PFS.xlsx")
```


Add histology, stage, treatment type, median PFS
		Strat by response and p-value (tableone)...fischers exact?
		
Need to resolve additional variables
		
```{r}
response <- response %>%
  rename("RNASeq" = Sample_ID) %>%
  filter(Cancer_Type == "Melanoma")

io <- io %>%
  rename("AvatarKey" = id) %>%
  select(AvatarKey, medication, OS_IO_M) %>%
  rename("IO" = medication,
         "PFS" = OS_IO_M)

time <- time %>%
  select(id, start) %>%
  rename("AvatarKey" = id)

# Is OS the same as PFS? in this data? average this? 

clin <- clin %>%
  rename("AvatarKey" = ORIENAvatarKey)

clin <- merge(response, clin)
clin <- merge(clin, extra_clin)
clin <- merge(clin, hist)
clin <- merge(clin, io)
clin <- merge(clin, time)

diagnosis <- diagnosis %>%
  select(AvatarKey, ClinGroupStage, CurrentlySeenForPrimaryOrRecurr) %>%
  rename("Stage" = ClinGroupStage) %>%
  filter(AvatarKey %in% clin$AvatarKey)

#clin <- merge(clin, diagnosis)


# outcomes <- read.csv("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210712_Outcomes_V4.csv") %>%
#   filter(AvatarKey %in% clin$AvatarKey) %>%
#   select(AvatarKey, )

# clin <- merge(clin, outcomes)
```



```{r}
# table(clin$Response)
# table(clin$Sex)
# table(clin$Age.At.Specimen.Collection)
# table(clin$Stage)
# table(clin$Histology)
# table(clin$ClinGroupStage)
```

```{r}
clin <- clin %>%
  mutate(Response = ifelse(Response == 0, "Non-Responder", "Responder"),
         Age = as.double(Age.At.Specimen.Collection),
         dif = start - as.double(Age.At.Specimen.Collection),
          `Sample within 1 year of IO start` = ifelse(dif > 1, "No", "Yes"))
```

<!-- Make age a categorial variable  -->
<!-- ```{r} -->
<!-- clin <- clin %>% -->
<!--   mutate(Response = ifelse(Response == 0, "Non-Responder", "Responder"), -->
<!--          Age = case_when(Age.At.Specimen.Collection >= 80  & Age.At.Specimen.Collection <= 89.99 ~ '80-89', -->
<!--                          Age.At.Specimen.Collection >= 70  & Age.At.Specimen.Collection <= 79.99 ~ '70-79', -->
<!--                          Age.At.Specimen.Collection >= 60  & Age.At.Specimen.Collection <= 69.99 ~ '60-69', -->
<!--                          Age.At.Specimen.Collection >= 50  & Age.At.Specimen.Collection <= 59.99 ~ '50-59', -->
<!--                          Age.At.Specimen.Collection >= 40  & Age.At.Specimen.Collection <= 49.99 ~ '40-49', -->
<!--                          Age.At.Specimen.Collection >= 30  & Age.At.Specimen.Collection <= 39.99 ~ '30-39', -->
<!--                          Age.At.Specimen.Collection >= 20  & Age.At.Specimen.Collection <= 29.99 ~ '20-29', -->
<!--                          Age.At.Specimen.Collection >= 10  & Age.At.Specimen.Collection <= 19.99 ~ '10-19',)) -->

<!-- ``` -->

<!-- Clean up stage -->
<!-- ```{r} -->
<!-- clin <- clin %>% -->
<!--   mutate(Stage = case_when(Stage == "0a" ~ 'Stage 0', -->
<!--                           Stage == "I" | Stage == "IA" | Stage == "IB" ~ "Stage 1", -->
<!--                           Stage == "II" | Stage == "IIA" | Stage == "IIB" | Stage == "IIC" ~ "Stage 2", -->
<!--                           Stage == "III" | Stage == "IIIB" | Stage == "IIIC" ~ "Stage 3", -->
<!--                           Stage == "IV" | Stage == "IVA" | Stage == "IVC" ~ "Stage 4", -->
<!--                           Stage == "Unknown/Not Reported" | Stage == "No TNM applicable for this site/histology combination" | Stage == "Unknown/Not Applicable" ~ "NA",)) -->

<!-- ``` -->

simplify treatment groups
```{r}
clin <- clin %>%
  mutate(IO = ifelse(IO == "Atezolizumab" | IO == "Pembrolizumab" | IO == "Nivolumab", "Anti-PD1/PDL1",
                     ifelse(IO == "Ipilimumab", "Anti-CTLA4", 
                            ifelse(IO == "Ipilimumab+Nivolumab", "Anti-CTLA4 + anti-PD1/PDL1", NA))))
```


```{r}
variables_listed <- c("Age", "Sex", "IO", "PFS", "Sample within 1 year of IO start")

cat_vars <- c("Sex", "IO", "Sample within 1 year of IO start")

rcc <- CreateTableOne(vars = variables_listed, strata = "Response", data = clin, factorVars = cat_vars)
tab <- print(rcc, noSpaces = TRUE, quote = FALSE, formatOptions = list(big.mark = ","))
#tab <- print(rcc, nonnormal = biomarkers, formatOptions = list(big.mark = ","))

```

```{r}
write.csv(tab, file = "../figures/table1.csv")
```


#  check out IO start and sample timeline
```{r}
io_start <- time %>%
  select(id, start) %>%
  rename("AvatarKey" = id)

samp_time <- clin %>%
  select(AvatarKey, RNASeq, Age.At.Specimen.Collection) %>%
  mutate(samp.age = as.double(Age.At.Specimen.Collection)) 

io_start <- left_join(samp_time, io_start) %>%
  mutate(IO.start = start - samp.age) %>%
  mutate(biopsy = 0)
```

plot
```{r}
io_start <- io_start %>%
  arrange(IO.start) 

g <- ggplot() +
  geom_segment(data=io_start, aes(y=RNASeq, yend=RNASeq, x=-3, xend=5), size=0.15) +
  geom_dumbbell(data=io_start, aes(y=RNASeq, x=biopsy, xend=IO.start),
linewidth =1.5, color="black", size_x=3, size_xend = 3, colour_x = "red3", colour_xend = "cornflowerblue") +
  theme(panel.grid.major.x=element_line(size=0.05)) + labs(x = "Years", y = "Patients")

g
```
```{r}
ggsave(plot = g, "../figures/io_start_timeline.png", width = 3, height = 8, dev = "png", dpi = 600)
```


