---
title: "create_counts_input"
author: "Caroline Wheeler"
date: "11/21/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(exoticpackage)
```

```{r}
# k2bout with all filters
# counts <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/k2bout_filt.txt")

# k2bout with human transcript filter
# counts <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/k2bout_humanRNAfilt.txt")

# k2bout with no filters
k2 <- read.delim("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/k2bout.txt")

# un-normalized counts, with decontam 
counts <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_unnormalized-microbes.csv")

# kraken database
kraken.met <- read.delim("/fs/ess/PAS1695/exoticpipe/external-data/kraken2-metaphlan-noplants.txt")
```


```{r}
kraken.met <- kraken.met %>%
  rename("Taxonomy" = d__Eukaryota)

taxa <- exoticpackage::assign_taxonomy(kraken.met, counts)

taxa <- taxa %>%
  rename("count" = "exo.ra")
```


save
```{r}
# write.csv(taxa, "/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_counts-with-taxonomy_filtered.csv")
# write.csv(taxa, "/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_counts-with-taxonomy-humanRNA-filter.csv")
write.csv(taxa, "/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_unnormalized-microbes-with-taxonomy.csv")
```


