---
title: "exomel - stacked bar"
author: "Caroline Wheeler"
date: "7/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(forcats)
library(ggforce)
library(patchwork)
```

read in data 
```{r}
taxa <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_counts-with-taxonomy-humanRNA-filter.csv")
clin <- read.table("/fs/ess/PAS1695/projects/exorien/data/IO_NOVA_clin.txt", header = TRUE) %>%
  dplyr::rename("sample" = Sample_ID) %>%
  filter(Cancer_Type == "Melanoma")
```

filter to iorig/exorien overlap
```{r}
taxa <- taxa %>%
  filter(taxa$sample %in% clin$sample)
```

```{r}
get_phyl_ra <- function(exora){
  exora.phyl <- exora %>%
  filter(microbe != "Homo.sapiens") %>%
  group_by(sample, phylum) %>%
  summarise(count = sum(count, na.rm = T)) %>%
  as.data.frame()
}
```

```{r}
taxa <- taxa %>%
  filter(!is.na(phylum))

exora.p <- get_phyl_ra(taxa)

large.phyls <- exora.p %>% 
  group_by(phylum) %>%
  dplyr::summarize(median.count = mean(count)) %>%
  arrange(desc(median.count)) %>%
  mutate(x = row_number()) %>%
  dplyr::filter(x <= 7)

large.phyls <- large.phyls$phylum
tmp <- exora.p %>% arrange(desc(count))
sampord.orter <- tmp$sample
```

combine with response data
```{r}
exora.p.hist <- merge(clin, exora.p)
```

```{r}
exora.p.hist <- exora.p.hist %>%
   mutate(phylum = ifelse(phylum %in% large.phyls, phylum, "Other"),
          phylum = gsub("^p__", "", phylum))
#          phylum = ifelse(phylum == "unclassified-c__Cryptophyceae", "Cryptophyceae", phylum))
```

prep for plot
```{r}
ord <- exora.p.hist %>%
  group_by(sample) %>%
  summarize(total = sum(count))

ord <- ord[order(ord$total),]
plotOrder <- ord$sample
exora.p.hist <- merge(ord, exora.p.hist)
exora.p.hist <- exora.p.hist %>%
  dplyr::mutate(sample = fct_reorder(sample, dplyr::desc(total)))

# exora.p.hist$phylum <- factor(exora.p.hist$phylum, levels = c("Other", "Actinobacteria", "Bacteroidetes", "Basidiomycota", "Firmicutes","Cryptophyceae", "Proteobacteria", "Uroviricota"))

exora.p.hist$phylum <- factor(exora.p.hist$phylum, levels = c("Other", "Actinobacteria", "Ascomycota", "Bacteroidetes", "Firmicutes", "Fusobacteria", "Proteobacteria", "Uroviricota"))

exora.p.hist <- exora.p.hist %>%
  mutate(Response = ifelse(Response == 0, "Non-Responder", "Responder"))

# combine 'Other'
exora.p.hist <- exora.p.hist %>%
  group_by(sample, Response, phylum) %>%
  summarize(count = sum(count))
```

plot
```{r}
g <- exora.p.hist %>% 
  #filter(sample != "SL362815") %>%
  ggplot(aes(x = sample, y = log(count), fill = phylum)) +
    geom_bar( stat = "identity") +
    labs(x = "", y = "") +
    scale_fill_manual(values = c("darkslateblue","red3", "darkgoldenrod2", "darkgreen", "salmon2", "plum", "cornflowerblue", "deeppink4"), name = "Taxa") +
    theme_minimal(base_size = 7) +
    theme(axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(),
          axis.text.y = element_blank(),
          panel.grid.major = element_blank())  +
  facet_row(vars(Response), scales = "free_x", space = "free") +
   theme(
    text = element_text(size = 7), legend.position = "bottom") 

g

ggsave(g, file = "../../figures/fig3_stackedbar_Ht_filt_logged.png", dev = "png", width = 4.5, height = 4)
#ggsave(g, file = "../../figures/fig3_stackedbar_Ht_filt.png", dev = "png", width = 4.5, height = 4)
#ggsave(g, file = "../figures/fig1_stackedbar.svg", dev = "svg", width = 7, height = 6)
```

